### PR TITLE
Clean up code and fix a few bugs

### LINKED ISSUE #6: Docstring incorrect for Server `security` argument
https://github.com/invenia/FTPServer.jl/blob/master/src/FTPServer.jl#L72
Should say ```(options: `:none`, `:implicit`, `:explicit`)``` instead of ```(options: `:none`, `:implicity`, `:explicity`)```

### PR DESCRIPTION
**Pull request by fchorney**
Closes #6 

Aside from closing that small docs issue, it was noticed that the julia code calling the python script was incorrect. It was setting a flag that didn't exist, and a bug was fixed where the first line returned by the command wasn't the ip/port. 

The python code `server.py` was cleaned up, and a few small changes were made. For one, the cert is now signed with SHA256 instead of SHA1, and the main function has been split up into a few functions.

Initially I was looking into this due to an SSL error we saw, but it turns out that is an actual OpenSSL issue with version `1.1.1e`.

### CODE REVIEW

File: src/FTPServer.jl [hunk 1]
```diff
@@ -84,14 +84,22 @@ function Server(
 
     cmd = `$PYTHON_CMD $SCRIPT $username $password $homedir --permissions $permissions`
     if security != :none
-        cmd = `$cmd --tls $security --cert-file $CERT --key-file $KEY --gen-certs TRUE`
+        cmd = `$cmd --tls $security --cert-file $CERT --key-file $KEY --gen-certs-dir $ROOT`
```
Comment (omus) [inline src/FTPServer.jl]: `CERT` and `KEY` are currently full paths instead of just file names

File: src/server.py [hunk 2]
```diff
@@ -26,8 +26,8 @@ def create_self_signed_cert(cert_dir, cert_file, key_file, hostname):
     # from https://gist.github.com/ril3y/1165038
     cert_path = realpath(join(cert_dir, cert_file))
     key_path = realpath(join(cert_dir, key_file))
-    if not exists(cert_path) or not exists(key_path):
 
+    if not exists(cert_path) or not exists(key_path):
```
Comment (omus) [inline src/server.py]: If you're calling a function called `create_self_signed_cert` shouldn't we always create these files?

File: src/FTPServer.jl (hunk 1 above)
Comment (fchorney) [reply src/FTPServer.jl]: yeah, the python code uses realpath so it does end up working. I'm unsure if I should modify the python code to *only* do what we need it to do. Currently it has a few arguments we don't use, and stuff like that. Not sure it really needs to be "generic" so to speak since it's being used specifically for this package.

Comment (fchorney) [reply src/FTPServer.jl]: If I modify it to just do what we need it to do then I can fix up the arguments and whatnot so they potentially make more sense.

File: src/server.py (hunk 2 above)
Comment (fchorney) [reply src/server.py]: Good point.

File: src/FTPServer.jl (hunk 1 above)
Comment (omus) [reply src/FTPServer.jl]: I suppose we can leave this as is and just open an issue. I think in the long term probably just allowing `--cert-file` to take a full path and not supplying a `--gen-certs-dir` would be reasonable. That would mean we'd need a flag to trigger the creation of the certs (by default it would just reference pre-created certs)

Comment (fchorney) [reply src/FTPServer.jl]: Well, if I substantially change the python script, I don't think that would be breaking in any way, so I could change it up. Unless we just don't want to have too many changes in this one PR.

**Comment by mattBrzezinski** [comment]
X-Posting the relevant OpenSSL issues:

- https://github.com/openssl/openssl/issues/11381
- https://github.com/openssl/openssl/issues/11378

File: Project.toml [hunk 3]
```diff
@@ -11,7 +11,7 @@ Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
 
 [compat]
 Conda = "1.3"
-Memento = "0.12"
+Memento = "1.0"
```
Comment (omus) [inline Project.toml]: Using `1.0` limits us to `1.0.x`
```suggestion
Memento = "1"
```

File: test/runtests.jl [hunk 4]
```diff
@@ -19,8 +21,16 @@ using Test
             @test resp.code == 226
         end
     end
-    @testset "ssl - $mode" for mode in (:explicit, :implicit)
-        FTPServer.serve(; security=mode) do server
+    @testset "no-ssl debug true" begin
```
Comment (omus) [inline test/runtests.jl]: Should we also include the upload test we used to reproduce this problem?

File: Project.toml (hunk 3 above)
Comment (iamed2) [reply Project.toml]: That is incorrect, but I still prefer your suggestion

File: test/runtests.jl (hunk 4 above)
Comment (fchorney) [reply test/runtests.jl]: I wasn't sure if we wanted to add that here or in a separate PR

Comment (omus) [reply test/runtests.jl]: Ah ok, lets just not forget
